###########################
#    General Variables    #
###########################
variable "aws_region" {
  type        = string
  description = "This value will storage the region of the AWS account"
}

variable "temporal_folder" {
  type        = string
  description = "This variables will be used to indicate what is the path of the tmp folder"
}

variable "lambdas_folder_path" {
  type        = string
  description = "This variable will be used to indicate where the code folder of all the lambdas is"
}

variable "training_service_code_path" {
  type        = string
  description = "This variables will be used to indicate where the code folder of the Training service is located"
}

variable "listener_rest_code_path" {
  type        = string
  description = "This variables will be used to indicate where the code folder of the Listener REST is located"
}

variable "common_code_path" {
  type        = string
  description = "This variable will be used to indicate where the common code folder (shared between services) is located"
}

variable "vpc_id" {
  type        = string
  description = "The identifier of the VPC where all the instances will be deployed"
}

variable "subnet_id" {
  type        = string
  description = "The identifier of the Subnet where all the instances will be deployed"
}


###########################
#       S3 Variables      #
###########################
variable "datasets_s3" {
  type        = map(string)
  description = "This variable will be used to create a S3 that will be used to host all the datasets that the users will store in the platform"
}

variable "filestransfer_s3" {
  type        = map(string)
  description = "This variable will be used to create a S3 that will be used to store files that will be need to be transfer from the EC2 to the User or in the other way"
}

variable "mlflow_artifacts_s3" {
  type        = map(string)
  description = "This variable will be used to create a S3 that will be used to store all the artifacts that are generated by the MlFlow Server"
}


##########################
#  ApiGateway Variables  #
##########################
variable "api_gateway_name" {
  type        = string
  description = "The name that the ApiGateway will has"
}

variable "api_gateaway_s3_resource" {
  type        = map(string)
  description = "This variable will be to describe the information of the resource in charge of connect the s3 with the API GateWay"
}

variable "api_gateaway_ec2_resource" {
  type        = map(string)
  description = "This variable will be to describe the information of the resource in charge of connect the ec2 training server with the API GateWay"
}


###########################
#       EC2 Variables     # 
###########################
variable "training_server" {
  type        = map(string)
  description = "This variable will be used as a dictionary of all the configuration related to the Training Server"
}

variable "mlflow_server" {
  type        = map(string)
  description = "This variable will be used as a dictionary of all the configuration related to the MlFlow Server"
}


###########################
#     Lambda Variables    # 
###########################
variable "authentication_lambda" {
  type        = map(string)
  description = "This variable will be used to describe the lambda of authentication"
}

variable "get_training_status_lambda" {
  type        = map(string)
  description = "This variable will be used to describe the lambda that will execute the code to get the status of some training"
}

variable "delete_data_lambda" {
  type        = map(string)
  description = "Information about the lambda of delete data"
}

variable "training_request_lambda" {
  type        = map(string)
  description = "Information about the lambda that will be used as a proxy to make request to start a training"
}

variable "authorizer_lambda" {
  type        = map(string)
  description = "Information about the lambda authorizer that validates API tokens"
}

variable "get_prediction_lambda" {
  type        = map(string)
  description = "Information about the lambda that will proxy prediction requests to the Training Server"
}


###########################
#    OpenCode Variables   #
###########################
variable "opencode_api_key" {
  type        = string
  description = "API key for OpenCode Go LLM service"
  sensitive   = true
}

variable "email_of_notification" {
  type        = string
  description = "Email address to receive CloudWatch alarm notifications"
}